package com.dillon.starsectormarines.battle.balance;

import com.dillon.starsectormarines.battle.balance.TtkHarness.Cover;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Defender;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Measurement;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Scenario;
import com.dillon.starsectormarines.battle.infantry.EquipmentGrade;
import com.dillon.starsectormarines.battle.infantry.ExperienceTier;
import com.dillon.starsectormarines.battle.infantry.MarineWeapon;
import com.dillon.starsectormarines.battle.infantry.SoldierAptitude;
import com.dillon.starsectormarines.battle.infantry.SoldierProfile;
import com.dillon.starsectormarines.battle.unit.UnitType;
import com.dillon.starsectormarines.marine.MarineArmorPattern;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Produces the time-to-kill table
 * {@code progression-nouns.md} defines the quality model this report tunes
 * against, and guards the structural relationships that must survive any
 * tuning pass.
 *
 * <p>The report is a set of slices through one baseline — pulse rifle, Service
 * grade, a Regular/Steady soldier, half of effective range, defender in the
 * open — because that is the row S1's target table is authored against. A full
 * cross product of weapon × grade × experience × armor × range × cover would
 * be thousands of scenarios and would bury the four comparisons that actually
 * drive a decision.
 *
 * <p>Written to {@code build/reports/balance/ttk-baseline.md} so a tuning pass
 * can diff two runs. The assertions are separate and deliberately loose: they
 * check that better kit kills faster, cover and armor slow a kill down, and
 * every baseline fight resolves at all. Absolute targets stay in the story
 * document, where changing them is a design decision rather than a test edit.
 */
class TtkReportTest {

    /** Lower than the harness default: this report measures ~50 scenarios, and the guarded comparisons are wide enough to hold at this precision. */
    private static final int TRIALS = 120;

    private static final SoldierProfile GREEN =
            new SoldierProfile(SoldierAptitude.STEADY, ExperienceTier.GREEN.minimumXp);
    private static final SoldierProfile REGULAR = SoldierProfile.REGULAR;
    private static final SoldierProfile VETERAN =
            new SoldierProfile(SoldierAptitude.GIFTED, ExperienceTier.VETERAN.minimumXp);
    private static final SoldierProfile ELITE =
            new SoldierProfile(SoldierAptitude.EXCEPTIONAL, ExperienceTier.ELITE.minimumXp);

    private static final Defender MILITIA = Defender.bare("militia", UnitType.MILITIA);
    private static final Defender ALIEN = Defender.bare("alien", UnitType.ALIEN);
    private static final Defender SWARM_RUNNER = Defender.bare("swarm runner", UnitType.SWARM_RUNNER);
    private static final Defender UNARMORED = Defender.armored("marine, unarmored", MarineArmorPattern.ARMORLESS);
    private static final Defender MID_ARMOR = Defender.armored("marine, T3 armor", MarineArmorPattern.ARMY_GREEN);
    private static final Defender HEAVY_ARMOR = Defender.armored("marine, T4 armor", MarineArmorPattern.RED_ELITE);

    private static final float BASELINE_RANGE_FRACTION = 0.5f;

    @Test
    void reportsTimeToKillAcrossTheTuningSlices() {
        StringBuilder report = new StringBuilder();
        report.append("# Time-to-kill baseline\n\n")
                .append("Generated by `TtkReportTest`. ").append(TRIALS)
                .append(" trials per row; `+/-` is the standard error of the mean.\n")
                .append("Unless a table says otherwise: pulse rifle, Service grade, Regular/Steady soldier,\n")
                .append("50% of effective range, defender in the open, stationary shooter, no return fire.\n");

        List<Measurement> byWeapon = new ArrayList<>();
        for (MarineWeapon weapon : new MarineWeapon[]{
                MarineWeapon.FIELD_RIFLE, MarineWeapon.PULSE_RIFLE, MarineWeapon.SMG, MarineWeapon.DMR}) {
            for (Defender defender : new Defender[]{
                    MILITIA, UNARMORED, MID_ARMOR, HEAVY_ARMOR, ALIEN, SWARM_RUNNER}) {
                byWeapon.add(TtkHarness.measure(new Scenario(weapon, EquipmentGrade.SERVICE,
                        REGULAR, defender, BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Weapon vs target", "weapon",
                byWeapon, m -> m.scenario().weapon().displayName());

        List<Measurement> byGrade = new ArrayList<>();
        for (EquipmentGrade grade : EquipmentGrade.values()) {
            for (Defender defender : new Defender[]{UNARMORED, MID_ARMOR, HEAVY_ARMOR}) {
                byGrade.add(TtkHarness.measure(new Scenario(MarineWeapon.PULSE_RIFLE, grade,
                        REGULAR, defender, BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Equipment grade ladder", "grade",
                byGrade, m -> m.scenario().grade().displayName);

        List<Measurement> byProfile = new ArrayList<>();
        for (SoldierProfile profile : new SoldierProfile[]{GREEN, REGULAR, VETERAN, ELITE}) {
            for (Defender defender : new Defender[]{UNARMORED, MID_ARMOR}) {
                byProfile.add(TtkHarness.measure(new Scenario(MarineWeapon.PULSE_RIFLE,
                        EquipmentGrade.SERVICE, profile, defender,
                        BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Soldier ladder (experience + aptitude together)", "soldier",
                byProfile, m -> m.scenario().profile().experienceTier().displayName
                        + " / " + m.scenario().profile().aptitude().displayName);

        List<Measurement> byCoverAndRange = new ArrayList<>();
        for (Cover cover : Cover.values()) {
            for (float fraction : new float[]{0.25f, 0.5f, 0.9f}) {
                byCoverAndRange.add(TtkHarness.measure(new Scenario(MarineWeapon.PULSE_RIFLE,
                        EquipmentGrade.SERVICE, REGULAR, UNARMORED, fraction, cover), TRIALS));
            }
        }
        appendTable(report, "Cover and range (vs unarmored marine)", "cover",
                byCoverAndRange, m -> m.scenario().cover().label);

        List<Measurement> everyRow = new ArrayList<>();
        everyRow.addAll(byWeapon);
        everyRow.addAll(byGrade);
        everyRow.addAll(byProfile);
        everyRow.addAll(byCoverAndRange);
        appendUnresolvedCallout(report, everyRow);

        writeReport(report.toString());

        assertLethalityRelationships(byWeapon, byGrade, byCoverAndRange);
    }

    /**
     * Guards the direction of every lever, not its magnitude. Each comparison
     * uses the widest available gap and a margin well outside the sampling
     * noise, so a tuning pass that legitimately narrows a gap does not trip
     * these, but a wiring mistake that inverts or flattens one does.
     */
    private static void assertLethalityRelationships(List<Measurement> byWeapon,
                                                     List<Measurement> byGrade,
                                                     List<Measurement> byCoverAndRange) {
        // Deliberately scoped to the pulse rifle rather than every weapon: as
        // of this baseline the FIELD RIFLE cannot kill an armored marine at
        // all — 0 of 120 trials inside a two-minute timeout — and the militia
        // row only resolves a quarter of the time. That is the measured
        // headline S1 Slice 1 exists to fix, and it belongs in the report's
        // unresolved-row callout where its numbers are visible, not encoded as
        // a pass/fail gate whose meaning silently flips after tuning. The
        // pulse rifle is the baseline every other table is expressed against,
        // so a row of it failing to resolve means the harness itself broke.
        for (Measurement m : byWeapon) {
            if (m.scenario().weapon() != MarineWeapon.PULSE_RIFLE) continue;
            assertTrue(m.fullyResolved(),
                    () -> "the baseline pulse-rifle engagement should always resolve, but "
                            + describe(m) + " killed in only " + m.kills()
                            + " of " + m.trials() + " trials");
        }

        Measurement surplus = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SURPLUS
                && m.scenario().defender() == UNARMORED);
        Measurement masterwork = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.MASTERWORK
                && m.scenario().defender() == UNARMORED);
        assertTrue(masterwork.meanTtkSeconds() < surplus.meanTtkSeconds(),
                () -> "masterwork kit should kill faster than surplus, but measured "
                        + fmt(masterwork.meanTtkSeconds()) + "s vs " + fmt(surplus.meanTtkSeconds()) + "s");

        Measurement unarmored = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SERVICE
                && m.scenario().defender() == UNARMORED);
        Measurement heavy = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SERVICE
                && m.scenario().defender() == HEAVY_ARMOR);
        assertTrue(heavy.meanTtkSeconds() > unarmored.meanTtkSeconds(),
                () -> "T4 armor should outlast no armor, but measured "
                        + fmt(heavy.meanTtkSeconds()) + "s vs " + fmt(unarmored.meanTtkSeconds()) + "s");

        Measurement open = pick(byCoverAndRange, m -> m.scenario().cover() == Cover.OPEN
                && m.scenario().rangeFraction() == 0.5f);
        Measurement hardCover = pick(byCoverAndRange, m -> m.scenario().cover() == Cover.HARD
                && m.scenario().rangeFraction() == 0.5f);
        assertTrue(hardCover.meanTtkSeconds() > open.meanTtkSeconds(),
                () -> "hard cover should extend a fight, but measured "
                        + fmt(hardCover.meanTtkSeconds()) + "s vs " + fmt(open.meanTtkSeconds()) + "s in the open");
    }

    /**
     * Lists every row where some trial never produced a kill. A mean built
     * from the lucky subset of an unresolved row reads as an ordinary number
     * in the table above, so the rows it was computed from are called out
     * here — an engagement the shooter cannot win is a design fact, not a
     * slow one.
     */
    private static void appendUnresolvedCallout(StringBuilder out, List<Measurement> rows) {
        List<Measurement> unresolved = rows.stream().filter(m -> !m.fullyResolved()).toList();
        out.append("\n## Unresolved engagements\n\n");
        if (unresolved.isEmpty()) {
            out.append("None — every row killed in every trial within ")
                    .append(fmt(TtkHarness.TRIAL_TIMEOUT_SECONDS)).append("s.\n");
            return;
        }
        out.append("Rows below did not kill in every trial within ")
                .append(fmt(TtkHarness.TRIAL_TIMEOUT_SECONDS))
                .append("s. Their mean TTK describes only the trials that resolved.\n\n");
        for (Measurement m : unresolved) {
            out.append("- ").append(describe(m))
                    .append(" (").append(m.scenario().grade().displayName)
                    .append(", ").append(m.scenario().cover().label).append(" cover, ")
                    .append(m.distanceCells()).append(" cells)")
                    .append(" — killed in ").append(m.kills()).append(" of ").append(m.trials())
                    .append(" trials\n");
        }
    }

    private static void appendTable(StringBuilder out, String title, String firstColumn,
                                    List<Measurement> rows, RowLabel label) {
        out.append("\n## ").append(title).append("\n\n")
                .append("| ").append(firstColumn)
                .append(" | target | dist | eff HP | TTK (s) | +/- | rounds | landed |\n")
                .append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |\n");
        for (Measurement m : rows) {
            out.append("| ").append(label.of(m))
                    .append(" | ").append(m.scenario().defender().label())
                    .append(" | ").append(m.distanceCells())
                    .append(" | ").append(fmt(m.effectiveHp()))
                    .append(" | ").append(m.fullyResolved() ? fmt(m.meanTtkSeconds())
                            : fmt(m.meanTtkSeconds()) + " (" + m.kills() + "/" + m.trials() + ")")
                    .append(" | ").append(fmt(m.standardErrorSeconds()))
                    .append(" | ").append(fmt(m.meanRoundsFired()))
                    .append(" | ").append(Math.round(m.landedFraction() * 100f)).append("%")
                    .append(" |\n");
        }
    }

    private static Measurement pick(List<Measurement> rows, Predicate<Measurement> match) {
        return rows.stream().filter(match).findFirst()
                .orElseThrow(() -> new IllegalStateException("no measurement matched the requested slice"));
    }

    private static String describe(Measurement m) {
        return m.scenario().weapon().displayName() + " vs " + m.scenario().defender().label();
    }

    private static String fmt(float v) {
        return Float.isNaN(v) ? "n/a" : String.format("%.2f", v);
    }

    private static void writeReport(String body) {
        Path out = Path.of("build", "reports", "balance", "ttk-baseline.md");
        try {
            Files.createDirectories(out.getParent());
            Files.writeString(out, body);
        } catch (IOException e) {
            throw new UncheckedIOException("failed to write the TTK report to " + out.toAbsolutePath(), e);
        }
        System.out.println("TTK baseline written to " + out.toAbsolutePath());
        System.out.println(body);
    }

    /** Names the varying axis of one table; the rest of the row is read off the measurement. */
    private interface RowLabel {
        String of(Measurement m);
    }
}
