package com.dillon.starsectormarines.battle.balance;

import com.dillon.starsectormarines.battle.balance.TtkHarness.Cover;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Defender;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Measurement;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Scenario;
import com.dillon.starsectormarines.battle.balance.TtkHarness.Screen;
import com.dillon.starsectormarines.battle.infantry.EquipmentGrade;
import com.dillon.starsectormarines.battle.infantry.ExperienceTier;
import com.dillon.starsectormarines.battle.weapon.WeaponDef;
import com.dillon.starsectormarines.battle.weapon.WeaponRegistry;
import com.dillon.starsectormarines.battle.infantry.SoldierAptitude;
import com.dillon.starsectormarines.battle.infantry.SoldierProfile;
import com.dillon.starsectormarines.battle.unit.UnitType;
import com.dillon.starsectormarines.marine.MarineArmorPattern;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Produces the time-to-kill table
 * {@code progression-nouns.md} defines the quality model this report tunes
 * against, and guards the structural relationships that must survive any
 * tuning pass.
 *
 * <p>The report is a set of slices through one baseline — pulse rifle, Service
 * grade, a Regular/Steady soldier, half of effective range, defender in the
 * open — because that is the row S1's target table is authored against. A full
 * cross product of weapon × grade × experience × armor × range × cover would
 * be thousands of scenarios and would bury the four comparisons that actually
 * drive a decision.
 *
 * <p>Written to {@code build/reports/balance/ttk-baseline.md} so a tuning pass
 * can diff two runs. The assertions are separate and deliberately loose: they
 * check that better kit kills faster, cover and armor slow a kill down, and
 * every baseline fight resolves at all. Absolute targets stay in the story
 * document, where changing them is a design decision rather than a test edit.
 */
class TtkReportTest {

    /** Lower than the harness default: this report measures ~50 scenarios, and the guarded comparisons are wide enough to hold at this precision. */
    private static final int TRIALS = 120;

    private static final SoldierProfile GREEN =
            new SoldierProfile(SoldierAptitude.STEADY, ExperienceTier.GREEN.minimumXp);
    private static final SoldierProfile REGULAR = SoldierProfile.REGULAR;
    private static final SoldierProfile VETERAN =
            new SoldierProfile(SoldierAptitude.GIFTED, ExperienceTier.VETERAN.minimumXp);
    private static final SoldierProfile ELITE =
            new SoldierProfile(SoldierAptitude.EXCEPTIONAL, ExperienceTier.ELITE.minimumXp);

    private static final Defender MILITIA = Defender.bare("militia", UnitType.MILITIA);
    private static final Defender ALIEN = Defender.bare("alien", UnitType.ALIEN);
    private static final Defender SWARM_RUNNER = Defender.bare("swarm runner", UnitType.SWARM_RUNNER);
    private static final Defender UNARMORED = Defender.armored("marine, unarmored", MarineArmorPattern.ARMORLESS);
    private static final Defender MID_ARMOR = Defender.armored("marine, T3 armor", MarineArmorPattern.ARMY_GREEN);
    private static final Defender HEAVY_ARMOR = Defender.armored("marine, T4 armor", MarineArmorPattern.RED_ELITE);

    /**
     * A representative authored screen, not a catalogued one. The point of the
     * slice below is what a bounded arc and a bounded pool are worth at all;
     * pinning it to one pattern's numbers would turn a structural measurement
     * into a balance assertion the catalog is free to move.
     */
    private static final float SCREEN_SOAK = 20f;
    private static final float SCREEN_ARC_DEGREES = 160f;
    private static final Defender SCREENED_FRONT = Defender.screened(
            "marine, T4 armor, screen forward", MarineArmorPattern.RED_ELITE,
            new Screen(SCREEN_SOAK, SCREEN_ARC_DEGREES, TtkHarness.FRONT_DEGREES));
    private static final Defender SCREENED_FLANK = Defender.screened(
            "marine, T4 armor, screen turned away", MarineArmorPattern.RED_ELITE,
            new Screen(SCREEN_SOAK, SCREEN_ARC_DEGREES, TtkHarness.FLANK_DEGREES));

    private static final float BASELINE_RANGE_FRACTION = 0.5f;

    @Test
    void reportsTimeToKillAcrossTheTuningSlices() {
        StringBuilder report = new StringBuilder();
        report.append("# Time-to-kill baseline\n\n")
                .append("Generated by `TtkReportTest`. ").append(TRIALS)
                .append(" trials per row; `+/-` is the standard error of the mean.\n")
                .append("Unless a table says otherwise: pulse rifle, Service grade, Regular/Steady soldier,\n")
                .append("50% of effective range, defender in the open, stationary shooter, no return fire.\n");

        List<Measurement> byWeapon = new ArrayList<>();
        for (WeaponDef weapon : new WeaponDef[]{
                WeaponRegistry.require(WeaponRegistry.STARTER_PRIMARY_ID), WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID), WeaponRegistry.require(WeaponRegistry.SMG_ID),
                WeaponRegistry.require(WeaponRegistry.SQUAD_AUTOMATIC_ID), WeaponRegistry.require(WeaponRegistry.DMR_ID)}) {
            for (Defender defender : new Defender[]{
                    MILITIA, UNARMORED, MID_ARMOR, HEAVY_ARMOR, ALIEN, SWARM_RUNNER}) {
                byWeapon.add(TtkHarness.measure(new Scenario(weapon, EquipmentGrade.SERVICE,
                        REGULAR, defender, BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Weapon vs target", "weapon",
                byWeapon, m -> m.scenario().weapon().displayName());

        List<Measurement> byGrade = new ArrayList<>();
        for (EquipmentGrade grade : EquipmentGrade.values()) {
            for (Defender defender : new Defender[]{UNARMORED, MID_ARMOR, HEAVY_ARMOR}) {
                byGrade.add(TtkHarness.measure(new Scenario(WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID), grade,
                        REGULAR, defender, BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Equipment grade ladder", "grade",
                byGrade, m -> m.scenario().grade().displayName);

        List<Measurement> byProfile = new ArrayList<>();
        for (SoldierProfile profile : new SoldierProfile[]{GREEN, REGULAR, VETERAN, ELITE}) {
            for (Defender defender : new Defender[]{UNARMORED, MID_ARMOR}) {
                byProfile.add(TtkHarness.measure(new Scenario(WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                        EquipmentGrade.SERVICE, profile, defender,
                        BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Soldier ladder (experience + aptitude together)", "soldier",
                byProfile, m -> m.scenario().profile().experienceTier().displayName
                        + " / " + m.scenario().profile().aptitude().displayName);

        // Experience alone, aptitude pinned. Since bands are issued with the
        // armour pattern and aptitude stays innate and per marine, the band is
        // what a player reads off a formation — so its span has to be
        // measurable without an aptitude roll mixed into it.
        List<Measurement> byBand = new ArrayList<>();
        for (ExperienceTier band : ExperienceTier.values()) {
            SoldierProfile profile = new SoldierProfile(SoldierAptitude.STEADY, band.minimumXp);
            for (Defender defender : new Defender[]{UNARMORED, MID_ARMOR}) {
                byBand.add(TtkHarness.measure(new Scenario(
                        WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                        EquipmentGrade.SERVICE, profile, defender,
                        BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            }
        }
        appendTable(report, "Experience band alone (aptitude held at Steady)", "band",
                byBand, m -> m.scenario().profile().experienceTier().displayName);

        // The campaign arc as one matchup. A company opens on raw numbers in bad
        // kit and should end as something that reads like a different species of
        // soldier, so the levers are measured compounded rather than one at a
        // time: band, grade, and the armour on the target all move together
        // because the armour pattern is what sets the band to begin with.
        SoldierProfile recruit = new SoldierProfile(SoldierAptitude.STEADY,
                ExperienceTier.GREEN.minimumXp);
        SoldierProfile superSoldier = new SoldierProfile(SoldierAptitude.STEADY,
                ExperienceTier.ELITE.minimumXp);
        List<Measurement> byArc = new ArrayList<>();
        for (Defender defender : new Defender[]{UNARMORED, HEAVY_ARMOR}) {
            byArc.add(TtkHarness.measure(new Scenario(
                    WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                    EquipmentGrade.SURPLUS, recruit, defender,
                    BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
            byArc.add(TtkHarness.measure(new Scenario(
                    WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                    EquipmentGrade.MASTERWORK, superSoldier, defender,
                    BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
        }
        appendTable(report, "Campaign arc (band + grade compounded)", "company",
                byArc, m -> m.scenario().grade() == EquipmentGrade.SURPLUS
                        ? "opening: Green / Surplus" : "endgame: Elite / Masterwork");

        // Directional mitigation, reported as its own contribution rather than
        // folded into the armour rows: the same suit, the same shot, and the
        // only thing that changes is which way the screen points.
        List<Measurement> byScreen = new ArrayList<>();
        for (Defender defender : new Defender[]{HEAVY_ARMOR, SCREENED_FRONT, SCREENED_FLANK}) {
            byScreen.add(TtkHarness.measure(new Scenario(
                    WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                    EquipmentGrade.SERVICE, REGULAR, defender,
                    BASELINE_RANGE_FRACTION, Cover.OPEN), TRIALS));
        }
        appendTable(report, "Directional mitigation (" + Math.round(SCREEN_SOAK)
                        + " damage soaked over " + Math.round(SCREEN_ARC_DEGREES)
                        + " degrees)", "screen",
                byScreen, m -> m.scenario().defender().screen() == null ? "none"
                        : m.scenario().defender().screen().facingDegrees() == TtkHarness.FRONT_DEGREES
                                ? "facing the shooter" : "turned away");

        List<Measurement> byCoverAndRange = new ArrayList<>();
        for (Cover cover : Cover.values()) {
            for (float fraction : new float[]{0.25f, 0.5f, 0.9f}) {
                byCoverAndRange.add(TtkHarness.measure(new Scenario(WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID),
                        EquipmentGrade.SERVICE, REGULAR, UNARMORED, fraction, cover), TRIALS));
            }
        }
        appendTable(report, "Cover and range (vs unarmored marine)", "cover",
                byCoverAndRange, m -> m.scenario().cover().label);

        List<Measurement> everyRow = new ArrayList<>();
        everyRow.addAll(byWeapon);
        everyRow.addAll(byGrade);
        everyRow.addAll(byProfile);
        everyRow.addAll(byBand);
        everyRow.addAll(byArc);
        everyRow.addAll(byScreen);
        everyRow.addAll(byCoverAndRange);
        appendUnresolvedCallout(report, everyRow);

        writeReport(report.toString());

        assertLethalityRelationships(byWeapon, byGrade, byCoverAndRange);
        assertBandIsWorthAboutAGradeStep(byBand, byGrade);
        assertTheArcEndsInSuperSoldiers(byArc);
        assertAScreenOnlyWorksFromTheFront(byScreen);
    }

    /**
     * Pins the two halves of the mitigation law end to end, through the real
     * firing pipeline rather than through the model in isolation: a screen
     * pointed at the shooter buys measurable time, and the same screen pointed
     * away buys none.
     *
     * <p>The flank bound is the more important of the two. A mitigation that
     * quietly worked all round would still show up as "the screen helps" on the
     * front row, and only the turned-away row can tell that apart from the
     * capability the design actually authorized.
     */
    private static void assertAScreenOnlyWorksFromTheFront(List<Measurement> byScreen) {
        Measurement unscreened = pick(byScreen, m -> m.scenario().defender() == HEAVY_ARMOR);
        Measurement front = pick(byScreen, m -> m.scenario().defender() == SCREENED_FRONT);
        Measurement flank = pick(byScreen, m -> m.scenario().defender() == SCREENED_FLANK);

        assertTrue(front.meanTtkSeconds() > unscreened.meanTtkSeconds(),
                () -> "a screen facing the shooter should extend the fight, but measured "
                        + fmt(front.meanTtkSeconds()) + "s vs " + fmt(unscreened.meanTtkSeconds())
                        + "s unscreened");
        // Loose enough for sampling noise at this trial count, tight enough that
        // an arc check that silently passed everything would fail here.
        assertTrue(flank.meanTtkSeconds() < unscreened.meanTtkSeconds() * 1.25d,
                () -> "a screen turned away from the shooter should buy nothing, but measured "
                        + fmt(flank.meanTtkSeconds()) + "s vs " + fmt(unscreened.meanTtkSeconds())
                        + "s unscreened");
    }

    /**
     * Pins the campaign arc: a company opens on raw numbers in bad kit and ends
     * as something that reads like a different species of soldier.
     *
     * <p>Measured as the exchange between the two ends rather than as either
     * side alone, because that is the thing a player actually experiences. The
     * endgame squad shoots better kit at a worse-protected target while the
     * opening squad shoots worse kit at a better-protected one, so band, grade,
     * and armour all compound in the same direction.
     *
     * <p>The bound is far below the measured figure and holds one weapon family
     * constant, so it is a floor rather than a target — upgrading weapon family
     * across the arc widens it further. It fails if a tuning pass flattens the
     * arc into a linear ladder, which would cost the campaign its sense of
     * having grown into something.
     */
    private static void assertTheArcEndsInSuperSoldiers(List<Measurement> byArc) {
        Measurement endgameKillingRecruits = pick(byArc,
                m -> m.scenario().grade() == EquipmentGrade.MASTERWORK
                        && m.scenario().defender() == UNARMORED);
        Measurement recruitsKillingEndgame = pick(byArc,
                m -> m.scenario().grade() == EquipmentGrade.SURPLUS
                        && m.scenario().defender() == HEAVY_ARMOR);

        double asymmetry = recruitsKillingEndgame.meanTtkSeconds()
                / endgameKillingRecruits.meanTtkSeconds();
        assertTrue(asymmetry > 8d,
                () -> "an endgame company should overmatch an opening one, but the exchange"
                        + " measured only " + String.format("%.1f", asymmetry) + "x");
    }

    /**
     * Pins the calibration that decided against widening the experience bands.
     *
     * <p>The band ladder was once described as a 1.23x effect, which is the
     * accuracy multiplier alone; measured end to end it also carries cooldown,
     * spread, and the one-off reflex delay. Against an unarmored marine the
     * measured Green-to-Elite span is materially wider than that, and lands in
     * the same range as the equipment-grade steps beside it — so a band is
     * worth roughly a grade step, which is a legible amount rather than noise.
     *
     * <p>Both bounds are loose enough to survive ordinary tuning and sampling
     * noise. The lower one fails if a change flattens bands back into
     * irrelevance; the upper one fails if bands grow to outweigh equipment,
     * which would make the armour pattern the only lever that matters since it
     * already sets the band ({@code progression-nouns.md}).
     */
    private static void assertBandIsWorthAboutAGradeStep(List<Measurement> byBand,
                                                         List<Measurement> byGrade) {
        Measurement green = pick(byBand, m -> m.scenario().profile().experienceTier()
                == ExperienceTier.GREEN && m.scenario().defender() == UNARMORED);
        Measurement elite = pick(byBand, m -> m.scenario().profile().experienceTier()
                == ExperienceTier.ELITE && m.scenario().defender() == UNARMORED);
        Measurement surplus = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SURPLUS
                && m.scenario().defender() == UNARMORED);
        Measurement masterwork = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.MASTERWORK
                && m.scenario().defender() == UNARMORED);

        double bandSpan = green.meanTtkSeconds() / elite.meanTtkSeconds();
        double gradeSpan = surplus.meanTtkSeconds() / masterwork.meanTtkSeconds();
        assertTrue(bandSpan > 1.4d,
                () -> "an issued band should be a visible difference, but Green-to-Elite"
                        + " measured only " + String.format("%.2f", bandSpan) + "x TTK");
        assertTrue(bandSpan < gradeSpan,
                () -> "equipment should still out-range veterancy, but the band span "
                        + String.format("%.2f", bandSpan) + "x met or beat the grade span "
                        + String.format("%.2f", gradeSpan) + "x");
    }

    /**
     * Guards the direction of every lever, not its magnitude. Each comparison
     * uses the widest available gap and a margin well outside the sampling
     * noise, so a tuning pass that legitimately narrows a gap does not trip
     * these, but a wiring mistake that inverts or flattens one does.
     */
    private static void assertLethalityRelationships(List<Measurement> byWeapon,
                                                     List<Measurement> byGrade,
                                                     List<Measurement> byCoverAndRange) {
        // Deliberately scoped to the pulse rifle rather than every weapon: as
        // of this baseline the FIELD RIFLE cannot kill an armored marine at
        // all — 0 of 120 trials inside a two-minute timeout — and the militia
        // row only resolves a quarter of the time. That is the measured
        // headline S1 Slice 1 exists to fix, and it belongs in the report's
        // unresolved-row callout where its numbers are visible, not encoded as
        // a pass/fail gate whose meaning silently flips after tuning. The
        // pulse rifle is the baseline every other table is expressed against,
        // so a row of it failing to resolve means the harness itself broke.
        for (Measurement m : byWeapon) {
            if (m.scenario().weapon() != WeaponRegistry.require(WeaponRegistry.PULSE_RIFLE_ID)) continue;
            assertTrue(m.fullyResolved(),
                    () -> "the baseline pulse-rifle engagement should always resolve, but "
                            + describe(m) + " killed in only " + m.kills()
                            + " of " + m.trials() + " trials");
        }

        Measurement surplus = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SURPLUS
                && m.scenario().defender() == UNARMORED);
        Measurement masterwork = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.MASTERWORK
                && m.scenario().defender() == UNARMORED);
        assertTrue(masterwork.meanTtkSeconds() < surplus.meanTtkSeconds(),
                () -> "masterwork kit should kill faster than surplus, but measured "
                        + fmt(masterwork.meanTtkSeconds()) + "s vs " + fmt(surplus.meanTtkSeconds()) + "s");

        Measurement unarmored = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SERVICE
                && m.scenario().defender() == UNARMORED);
        Measurement heavy = pick(byGrade, m -> m.scenario().grade() == EquipmentGrade.SERVICE
                && m.scenario().defender() == HEAVY_ARMOR);
        assertTrue(heavy.meanTtkSeconds() > unarmored.meanTtkSeconds(),
                () -> "T4 armor should outlast no armor, but measured "
                        + fmt(heavy.meanTtkSeconds()) + "s vs " + fmt(unarmored.meanTtkSeconds()) + "s");

        Measurement open = pick(byCoverAndRange, m -> m.scenario().cover() == Cover.OPEN
                && m.scenario().rangeFraction() == 0.5f);
        Measurement hardCover = pick(byCoverAndRange, m -> m.scenario().cover() == Cover.HARD
                && m.scenario().rangeFraction() == 0.5f);
        assertTrue(hardCover.meanTtkSeconds() > open.meanTtkSeconds(),
                () -> "hard cover should extend a fight, but measured "
                        + fmt(hardCover.meanTtkSeconds()) + "s vs " + fmt(open.meanTtkSeconds()) + "s in the open");
    }

    /**
     * Lists every row where some trial never produced a kill. A mean built
     * from the lucky subset of an unresolved row reads as an ordinary number
     * in the table above, so the rows it was computed from are called out
     * here — an engagement the shooter cannot win is a design fact, not a
     * slow one.
     */
    private static void appendUnresolvedCallout(StringBuilder out, List<Measurement> rows) {
        List<Measurement> unresolved = rows.stream().filter(m -> !m.fullyResolved()).toList();
        out.append("\n## Unresolved engagements\n\n");
        if (unresolved.isEmpty()) {
            out.append("None — every row killed in every trial within ")
                    .append(fmt(TtkHarness.TRIAL_TIMEOUT_SECONDS)).append("s.\n");
            return;
        }
        out.append("Rows below did not kill in every trial within ")
                .append(fmt(TtkHarness.TRIAL_TIMEOUT_SECONDS))
                .append("s. Their mean TTK describes only the trials that resolved.\n\n");
        for (Measurement m : unresolved) {
            out.append("- ").append(describe(m))
                    .append(" (").append(m.scenario().grade().displayName)
                    .append(", ").append(m.scenario().cover().label).append(" cover, ")
                    .append(m.distanceCells()).append(" cells)")
                    .append(" — killed in ").append(m.kills()).append(" of ").append(m.trials())
                    .append(" trials\n");
        }
    }

    private static void appendTable(StringBuilder out, String title, String firstColumn,
                                    List<Measurement> rows, RowLabel label) {
        out.append("\n## ").append(title).append("\n\n")
                .append("| ").append(firstColumn)
                .append(" | target | dist | eff HP | TTK (s) | +/- | rounds | landed |\n")
                .append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |\n");
        for (Measurement m : rows) {
            out.append("| ").append(label.of(m))
                    .append(" | ").append(m.scenario().defender().label())
                    .append(" | ").append(m.distanceCells())
                    .append(" | ").append(fmt(m.effectiveHp()))
                    .append(" | ").append(m.fullyResolved() ? fmt(m.meanTtkSeconds())
                            : fmt(m.meanTtkSeconds()) + " (" + m.kills() + "/" + m.trials() + ")")
                    .append(" | ").append(fmt(m.standardErrorSeconds()))
                    .append(" | ").append(fmt(m.meanRoundsFired()))
                    .append(" | ").append(Math.round(m.landedFraction() * 100f)).append("%")
                    .append(" |\n");
        }
    }

    private static Measurement pick(List<Measurement> rows, Predicate<Measurement> match) {
        return rows.stream().filter(match).findFirst()
                .orElseThrow(() -> new IllegalStateException("no measurement matched the requested slice"));
    }

    private static String describe(Measurement m) {
        return m.scenario().weapon().displayName() + " vs " + m.scenario().defender().label();
    }

    private static String fmt(float v) {
        return Float.isNaN(v) ? "n/a" : String.format("%.2f", v);
    }

    private static void writeReport(String body) {
        Path out = Path.of("build", "reports", "balance", "ttk-baseline.md");
        try {
            Files.createDirectories(out.getParent());
            Files.writeString(out, body);
        } catch (IOException e) {
            throw new UncheckedIOException("failed to write the TTK report to " + out.toAbsolutePath(), e);
        }
        System.out.println("TTK baseline written to " + out.toAbsolutePath());
        System.out.println(body);
    }

    /** Names the varying axis of one table; the rest of the row is read off the measurement. */
    private interface RowLabel {
        String of(Measurement m);
    }
}
