package com.dillon.starsectormarines.tools.tilesetauthoring;

import java.util.ArrayList;
import java.util.List;

/**
 * The sheet's contents written out for a reader rather than a loader.
 *
 * <p>A tileset is addressed by id, but an id is a poor description: nothing in
 * {@code doodad.ship.piece-014} says whether it is an office desk or a reactor
 * housing, and nothing in a pair of atlas coordinates says it either. Choosing
 * content from the JSON therefore means opening the atlas and counting cells.
 *
 * <p>Most of the choosing is now done by an LLM asked to assemble a map, which
 * reads whatever text is in the repository and cannot open the atlas at all. So
 * the card is the artifact that makes a sheet usable: one row per authored id,
 * with what it is, how much deck it covers, what cover it gives, how high it
 * stops a shot, which edge wants a wall, and the note and tags its author left.
 * It is generated on export and never edited by hand.
 */
public final class TilesetCatalogCard {

    private TilesetCatalogCard() {}

    /**
     * Render the card for a sheet.
     *
     * @param sheetName the base name shared by the atlas and its tileset
     * @param sheetPath the atlas path as the tileset declares it
     */
    public static String render(String sheetName, String sheetPath, int cellPx,
                                List<TilesetExport.Entry> entries,
                                List<TilesetExport.BlockSpec> blocks) {
        TilesetExport.Packing packing = TilesetExport.pack(entries, blocks);
        StringBuilder out = new StringBuilder();
        out.append("# ").append(sheetName).append(" tileset\n\n");
        out.append("Generated by the Tilesets page of `gradlew.bat layerAuthoring`. ")
                .append("Do not edit by hand — re-exporting the sheet overwrites it.\n\n");
        out.append("- atlas: `").append(sheetPath).append("`\n");
        out.append("- cell size: ").append(cellPx).append(" px\n");
        out.append("- extent: ").append(packing.columns()).append("x")
                .append(packing.rows()).append(" cells\n\n");

        List<TilesetExport.BlockSpec> present = new ArrayList<>();
        for (TilesetExport.BlockSpec spec : blocks) {
            if (packing.blockOrigins().containsKey(spec.id)) present.add(spec);
        }
        if (!present.isEmpty()) {
            out.append("## Blocks\n\n");
            out.append("A block is selected by id and used as one thing. An autotile block lets\n");
            out.append("the game pick which of its cells to draw from the surrounding walls; a\n");
            out.append("variant pool has no geometry and is picked by hashing the cell.\n\n");
            out.append("| id | layout | note | tags |\n|---|---|---|---|\n");
            for (TilesetExport.BlockSpec spec : present) {
                TilesetExport.Entry origin = originMember(entries, spec.id);
                out.append("| `").append(spec.id).append("` | ")
                        .append(TilesetExport.jsonLayout(spec.layout)).append(" | ")
                        .append(cell(origin == null ? "" : origin.note)).append(" | ")
                        .append(cell(origin == null ? "" : String.join(", ", origin.tags)))
                        .append(" |\n");
            }
            out.append('\n');
        }

        List<TilesetExport.Entry> doodads = new ArrayList<>();
        for (TilesetExport.Entry entry : entries) {
            if (entry.included && !entry.isBlockMember()) doodads.add(entry);
        }
        out.append("## Doodads\n\n");
        if (doodads.isEmpty()) {
            out.append("None.\n");
            return out.toString();
        }
        out.append("| id | cells | cover | half height | wall side | note | tags |\n");
        out.append("|---|---|---|---|---|---|---|\n");
        for (TilesetExport.Entry entry : doodads) {
            out.append("| `").append(entry.id).append("` | ")
                    .append(entry.footprintX).append("x").append(entry.footprintY).append(" | ")
                    .append(entry.cover).append(" | ")
                    .append(cell(entry.ballisticHalfHeight == null
                            ? "" : String.valueOf(entry.ballisticHalfHeight))).append(" | ")
                    .append(cell(entry.preferredWallSide)).append(" | ")
                    .append(cell(entry.note)).append(" | ")
                    .append(cell(String.join(", ", entry.tags))).append(" |\n");
        }
        return out.toString();
    }

    /**
     * Render the card for a sliced strip.
     *
     * <p>A strip has no cells, no footprints and no blocks, so the columns that
     * mean something about it are different ones: which frame the loader will
     * hand each id, which layer it draws on, and the label and description the
     * tileset carries for a reader. The frame number is the part worth writing
     * down — it is the sheet's only address, and it is assigned by order rather
     * than authored, so a reader who wants to check one against the picture has
     * nothing else to count with.
     */
    public static String renderStrip(String sheetName, String sheetPath,
                                     TilesetExport.StripSpec spec,
                                     List<TilesetExport.Entry> frames) {
        StringBuilder out = new StringBuilder();
        out.append("# ").append(sheetName).append(" tileset\n\n");
        out.append("Generated by the Tilesets page of `gradlew.bat layerAuthoring`. ")
                .append("Do not edit by hand — re-exporting the sheet overwrites it.\n\n");
        out.append("- atlas: `").append(sheetPath).append("`\n");
        out.append("- shape: sliced strip (`").append(spec.mode())
                .append("`, alpha ≥ ").append(spec.alphaThreshold())
                .append(", split on ").append(spec.minGap()).append(" clear columns)\n");
        out.append("- frames: ").append(frames.size()).append('\n');
        out.append("- drawn at 1/").append(String.format("%.4g", spec.scale()))
                .append(" of the raw art\n\n");
        out.append("## Tiles\n\n");
        if (frames.isEmpty()) {
            out.append("None.\n");
            return out.toString();
        }
        out.append("A sliced tile is selected by id; the frame column says which picture on\n");
        out.append("the strip that id resolves to, counting from the left.\n\n");
        out.append("| frame | id | name | layer | cover | passable | description | tags |\n");
        out.append("|---|---|---|---|---|---|---|---|\n");
        for (int frame = 0; frame < frames.size(); frame++) {
            TilesetExport.Entry entry = frames.get(frame);
            out.append("| ").append(frame).append(" | `").append(entry.id).append("` | ")
                    .append(cell(entry.label)).append(" | ")
                    .append(entry.layer).append(" | ")
                    .append(entry.cover).append(" | ")
                    .append(entry.passable ? "yes" : "no").append(" | ")
                    .append(cell(entry.note)).append(" | ")
                    .append(cell(String.join(", ", entry.tags))).append(" |\n");
        }
        return out.toString();
    }

    /**
     * A block's note is authored on whichever of its cells carries one, so the
     * card has something to show for a block that is described once rather than
     * nine times.
     */
    private static TilesetExport.Entry originMember(List<TilesetExport.Entry> entries, String blockId) {
        TilesetExport.Entry fallback = null;
        for (TilesetExport.Entry entry : entries) {
            if (!entry.included || !blockId.equals(entry.blockId)) continue;
            if (!entry.note.isEmpty() || !entry.tags.isEmpty()) return entry;
            if (fallback == null) fallback = entry;
        }
        return fallback;
    }

    /** A pipe or a newline in a note would break the row it sits in. */
    private static String cell(String text) {
        if (text == null || text.isBlank()) return "—";
        return text.replace("|", "\\|").replace("\n", " ").trim();
    }
}
